PIMA_DIABETES_DATASET = 'datasets/pima-indians-diabetes-data.csv'
PIMA_DIABETES_MODIFIED_DATASET = 'datasets/pima-indians-diabetes-modified-data.csv'
BGL_PAPER_DATASET = 'datasets/BGL-paper-dataset.csv'
SENSORS_DATA_0_ML = 'datasets/Acetone_0_ml.csv'
SENSORS_DATA_2_ML = 'datasets/Acetone_2_ml.csv'
SENSORS_DATA_10_ML = 'datasets/Acetone_10_ml.csv'
SENSORS_DATA_20_ML = 'datasets/Acetone_20_ml.csv'
SENSORS_DATA_40_ML = 'datasets/Acetone_40_ml.csv'
AIIMS_DAY_1_DATA = 'datasets/AIIMS_Day_1.csv'
AIIMS_COMP_DATA = 'datasets/AIIMS_Mandi_Complete_Details_1.csv'
FEATURES_DATA = 'reducedClassificationData/classification_features.csv'
FEATURE_LABELS = 'reducedClassificationData/classification_labels.csv'
REGRESSION_FEATURES = 'reducedClassificationData/regression_features.csv'
REGRESSION_LABELS = 'reducedClassificationData/regression_labels.csv'
RED_FEATURES_DIR = 'reducedClassificationData/'
TEST_DATA_SHEET = 'complete_test_data.csv'
SENSOR_TEST_DATA_DIR= '/Users/sangeeta/Downloads/Diabetes_test' #'C:/Users/ceo/Downloads/Diabetes_test'

MODELS = 'models/'
XGBOOST_CLASSIFIER = 'xg_boost_classifier.pkl'
XGBOOST_REGRESSOR = 'xgb_regressor.pkl'
DEC_TREE_REGRESSOR = 'dec_tree_regressor.pkl'
DEC_TREE_CLASSIFIER = 'dec_tree_classifier.pkl'
RAND_FOREST_CLASSIFIER = 'rand_forest_classifier.pkl'
KNEIGH_REGRESSOR = 'k_neigh_regressor.pkl'
KNEIGH_CLASSIFIER = 'k_neigh_classifier.pkl'
ENET_REGRESSOR = 'e_net_regressor.pkl'
ENET_CLASSIFIER = 'e_net_classifier.pkl'
LASSO_REGRESSOR = 'lasso_regressor.pkl'
LASSO_CLASSIFIER = 'lasso_classifier.pkl'
LINEAR_REGRESSOR = 'linear_regressor.pkl'
LINEAR_CLASSIFIER = 'linear_classifier.pkl'
GB_CLASSIFIER = 'gb_classifier.pkl'
MLP_CLASSIFIER = 'mlp_classifier.pkl'
RIDGE_REGRESSOR = 'ridge_regressor.pkl'
RIDGE_CLASSIFIER = 'ridge_classifier.pkl'
SVM_REGRESSOR = 'svm_regressor.pkl'
SVM_CLASSIFIER = 'SVM_classifier.pkl'
LSVM_CLASSIFIER = 'lsvm_classifier.pkl'
LOG_REGRESSOR = 'logistic_regressor.pkl'
LOG_CLASSIFIER = 'logistic_classifier.pkl'
BEST_MODELS_DIR = 'meta_results/best_meta_without_bgl'

NORM_CURVE_FIT_RESULTS = 'results/norm_fit_results/'
RESULTS = 'results/'
HYPERTUNE_RESULTS = RESULTS + 'hypertuning_results/'
NORM_FIGS = 'figs/norm_fit_curves/'
RAW_CURVE_FIT_RESULTS = 'results/raw_fit_results/'
RAW_FIGS = 'figs/raw_fit_curves/'
NORM_DATA_ANALYSIS_FIGS = 'figs/norm_data_analysis/'
RAW_DATA_ANALYSIS_FIGS = 'figs/raw_data_analysis/'

ACETONE_CONC = [2, 10, 20, 40] #, 40
SENSORS_VOLTAGE_DATA = [SENSORS_DATA_2_ML, SENSORS_DATA_10_ML, SENSORS_DATA_20_ML, SENSORS_DATA_40_ML]
PATIENT_COLUMN_NAMES = ['Timestamps',	'Temperature',	'Humidity', 'TGS826', 'TGS2603', 'TGS2610',	'TGS2620','Age', 'Gender',	'max_BP', 'min_BP',	'Heart_Beat', 'SPO2', 'Diabetes', 'BGL'] #	'TGS2602',	'TGS2620',	'TGS2603',	'TGS2610', 'TGS2600', 'TGS822',	'TGS826',	'MQ138',
TEST_DATA_COLUMN_NAMES = ['Timestamps',	'Temperature',	'Humidity', 'TGS826', 'TGS2603', 'TGS2610',	'TGS2620','Age', 'Gender',	'max_BP', 'min_BP',	'Heart_Beat', 'SPO2', 'Sample_No']
AGGREGATE_DATA_COLUMN_NAMES = ['Temperature',	'Humidity',	'TGS826', 'TGS2603', 'TGS2610',	'TGS2620'] # 'TGS2602',	'TGS2620',	'TGS2603',	'TGS2610', 'TGS2600', 'TGS822',	'TGS826',	'MQ138'
SINGULAR_DATA_COLUMN_NAMES = ['Age', 'Gender', 'Heart_Beat', 'SPO2', 'max_BP', 'min_BP', 'Diabetes']
TEST_SINGULAR_DATA_COLUMN_NAMES = ['Age', 'Gender', 'Heart_Beat', 'SPO2', 'max_BP', 'min_BP']
AGGREGATE_FUNC_DICT = {1: "max", 2: "min", 3: "median", 4: "mean"}
REGRESSION_RESULT_COLS = ['MODEL_NAME', 'FILTER', 'MAE_AVG', 'MAE_ERR', 'RMSE_AVG', 'RMSE_ERR', 'NEG_MSE_AVG', 'NMSE_ERR', 'NMSLogE_AVG', 'NMSLE_ERR', 'NMdAE', 'NMdAE_ERR', 'NMPD', 'NMPD_ERR']
CLASSIFICATION_RESULT_COLS = ['MODEL_NAME', 'FILTER', 'Accuracy', 'F1 Score', 'ROC Area']
ML_TASKS = ['regression', 'classification']
FILTERS = {1: 'Butterworth', 2: 'Chebyshev_1', 3: 'Chebyshev_2', 4: 'Elliptic'}
MAX_PADDING_LENGTH = 200
DATASET_FILE_DIRS = ['classificationData']#, 'regressionData']
SENSOR_COLS = ['TGS826', 'TGS2603', 'TGS2610',	'TGS2620'] #,	'MQ138', 'TGS2600', ,	'TGS822',	'TGS2602'


ACETONE_DATA_COL_NAMES = ['Sample_No', 'Temperature', 'Humidity', 'TGS2600', 'TGS2602', 'TGS2603', 'TGS2610', 'TGS2620', 'TGS822', 'TGS826'] #, 'MQ138'